import type {Metadata} from "next";

import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "character-simpson",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="es">
      <body className="container grid min-h-screen grid-rows-[auto,1fr,auto] bg-background  font-sans antialiased">
        <header className="text-xl font-bold leading-[4rem]">
          <Link href="/">Crea tu personaje simpson IA</Link>
        </header>
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} character-simpson
        </footer>
      </body>
    </html>
  );
}
